# Generated by Django 4.1.4 on 2023-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='user',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='myfileupload',
            name='my_file',
            field=models.BinaryField(),
        ),
    ]
