# Generated by Django 4.1.4 on 2023-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0003_remove_myfileupload_my_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('hostdata', models.CharField(max_length=1000000000000)),
            ],
        ),
    ]
