# Generated by Django 4.1.4 on 2023-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0004_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='hostdata',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
