# Generated by Django 4.1.4 on 2023-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0005_myfileupload_hostdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='null', max_length=50)),
                ('storage_consumed', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
