# Generated by Django 4.1.4 on 2023-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0006_userstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='storage_alloted',
            field=models.CharField(default=1024, max_length=10),
        ),
    ]
