# Generated by Django 4.1.4 on 2023-06-09 15:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0007_userstorage_storage_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='downloadcount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='filedata',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='filedata',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
