# Generated by Django 4.1.4 on 2023-06-09 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0009_remove_filedata_downloadcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfileupload',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
