# Generated by Django 4.1.4 on 2023-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0010_alter_myfileupload_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='file_size',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='myfileupload',
            name='status',
            field=models.CharField(default='Uploaded', max_length=10),
        ),
    ]
