# Generated by Django 4.1.4 on 2023-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0011_myfileupload_file_size_myfileupload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('portno', models.CharField(max_length=50)),
            ],
        ),
    ]
