# Generated by Django 4.1.4 on 2023-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0013_serverdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='assignedID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
