# Generated by Django 4.1.4 on 2023-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0016_myfileupload_del_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
