# Generated by Django 4.1.4 on 2023-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0017_userstorage_is_loggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='user',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
