# Generated by Django 4.1.4 on 2023-08-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0018_serverdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='hostdata',
        ),
        migrations.AddField(
            model_name='filedata',
            name='LastFileID',
            field=models.CharField(default=1, max_length=1000000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myfileupload',
            name='progress',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
